In [1]:
import numpy as np
import pandas as pd
from pandas import value_counts

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [6]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [11]:
X_train

age  gender  fever   cough       city
25   23    Male    NaN    Mild     Mumbai
67   65    Male   99.0    Mild  Bangalore
2    42    Male  101.0    Mild      Delhi
28   16    Male  104.0    Mild    Kolkata
57   49  Female   99.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
48   66    Male   99.0  Strong  Bangalore
94   79    Male    NaN  Strong    Kolkata
77    8  Female  101.0    Mild    Kolkata
73   34    Male   98.0  Strong    Kolkata
20   12    Male   98.0  Strong  Bangalore

[80 rows x 5 columns]

## 1. Aam Zindagi

In [13]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever

array([[100.8630137],
       [ 99.       ],
       [101.       ],
       [104.       ],
       [ 99.       ],
       [103.       ],
       [ 98.       ],
       [101.       ],
       [103.       ],
       [100.       ],
       [ 98.       ],
       [103.       ],
       [102.       ],
       [103.       ],
       [ 98.       ],
       [ 98.       ],
       [100.8630137],
       [101.       ],
       [100.       ],
       [ 98.       ],
       [104.       ],
       [ 98.       ],
       [102.       ],
       [102.       ],
       [104.       ],
       [102.       ],
       [104.       ],
       [102.       ],
       [100.       ],
       [100.8630137],
       [100.       ],
       [104.       ],
       [103.       ],
       [104.       ],
       [104.       ],
       [102.       ],
       [100.8630137],
       [101.       ],
       [100.       ],
       [ 98.       ],
       [101.       ],
       [100.       ],
       [ 98.       ],
       [101.       ],
       [ 98.       ],
       [10

In [16]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [15]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],

In [17]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [20]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city

array([[1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],


In [21]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [22]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age

array([[23],
       [65],
       [42],
       [16],
       [49],
       [83],
       [40],
       [51],
       [60],
       [10],
       [69],
       [46],
       [20],
       [70],
       [31],
       [71],
       [75],
       [64],
       [11],
       [81],
       [ 6],
       [23],
       [ 5],
       [74],
       [75],
       [33],
       [42],
       [82],
       [27],
       [38],
       [80],
       [51],
       [48],
       [12],
       [44],
       [69],
       [84],
       [19],
       [27],
       [80],
       [65],
       [ 5],
       [26],
       [20],
       [83],
       [15],
       [14],
       [16],
       [47],
       [10],
       [49],
       [65],
       [73],
       [17],
       [ 5],
       [82],
       [68],
       [51],
       [81],
       [64],
       [55],
       [83],
       [56],
       [64],
       [69],
       [72],
       [49],
       [38],
       [13],
       [71],
       [34],
       [47],
       [19],
       [73],
       [59],
       [66],
       [79],

In [23]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [24]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed

array([[ 23.       , 100.8630137,   1.       ,   0.       ,   0.       ,
          1.       ,   0.       ],
       [ 65.       ,  99.       ,   1.       ,   0.       ,   0.       ,
          0.       ,   0.       ],
       [ 42.       , 101.       ,   1.       ,   1.       ,   0.       ,
          0.       ,   0.       ],
       [ 16.       , 104.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 49.       ,  99.       ,   0.       ,   0.       ,   0.       ,
          0.       ,   1.       ],
       [ 83.       , 103.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 40.       ,  98.       ,   0.       ,   1.       ,   0.       ,
          0.       ,   1.       ],
       [ 51.       , 101.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   1.       ],
       [ 60.       , 103.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   0.       ],
       [ 10.       , 100.   

In [25]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

## Mentos Zindagi

In [27]:
from sklearn.compose import ColumnTransformer

In [28]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [31]:
transformer.fit_transform(X_train)

array([[100.8630137,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  23.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  65.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  42.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  16.       ],
       [ 99.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  49.       ],
       [103.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  83.       ],
       [ 98.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  40.       ],
       [101.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  51.       ],
       [103.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  60.       ],
       [100.       ,   0.   

In [32]:
transformer.fit_transform(X_train).shape

(80, 7)

In [33]:
transformer.transform(X_test)

array([[ 99.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  25.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  60.       ],
       [100.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  27.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  14.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  82.       ],
       [ 99.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  65.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  11.       ],
       [ 98.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  24.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  19.       ],
       [104.       ,   0.   

In [34]:
transformer.transform(X_test).shape

(20, 7)